- name: provision nodes
  hosts: all

  tasks:
  - name: Add epel-release repo
    ansible.builtin.dnf:
      name: epel-release
      state: present

  - name: enable powertools 
    ansible.builtin.command:  
      cmd: dnf config-manager --set-enabled powertools
#      warn: false

  - name: Add additional packages
    ansible.builtin.dnf:
      name: 
        - bash-completion
        - bind-utils
        - firewalld
        - git
        - openssh-clients
        - python3
        - python3-pip
        - net-tools
        - nfs-utils
      state: present

  - name: launch firewalld
    service: name=firewalld state=started enabled=yes

  - name: set firewalld default zone to 'trusted'
    command: firewall-cmd --set-default-zone=trusted
    
#  - name: Copy ssh config
#    copy:
#      src: files/config
#      dest: /root/.ssh/config
#      owner: root
#      group: root
#      mode: u+rw,u-x,g-rwx,o-rwx

#  - name: Copy ssh key
#    copy:
#      src: ../repofootloose2-cluster-key
#      dest: /root/.ssh/cluster-key
#      owner: root
#      group: root
#      mode: u+rw,u-x,g-rwx,o-rwx


