- name: provision nodes
  hosts: all

  tasks:
  - name: set up nfs dat folder
    file:
      path: /mnt/data
      state: directory
      owner: root
      group: root

  - name: nfs configs
    shell: 'echo "/mnt/data/ 192.168.122.0/24(rw,async,no_root_squash)" > /etc/exports.d/virt.exports'

  - name: start nfs service
    service:
      name: nfs-server
      enabled: yes
      state: started

