- name: provision nodes
  hosts: all

  tasks:
  - name: Add additional packages for kubernetes
    ansible.builtin.dnf:
      name: 
        - bash-completion
        - bind-utils
        - firewalld
        - git
        - iproute-tc
        - openssh-clients
        - python3
        - python3-pip
        - net-tools
        - nfs-utils
      state: present

